default:
  # Add any default values that will apply for multiple applications here.
  verbose: false                          # Increase output verbosity.
  auto_cleanup: true                      # Automatically remove any packaged artefacts after scanning completes.
  type: directory                         # Package source type, options=[repo, directory (default)].
  strict: true                            # If this optional flag is enabled, the exit code 4 indicates build failure during packaging.
  create_profile: false                   # Create a application profile if the one provided in AppName does not exist.
  sandbox_name: Release Candidate         # Name of the sandbox to use when running a sandbox scan or promoting a sandbox scan.
  # branch: main                          # Name of specific branch to scan.
  # version: 02 Jan 2006 15:04PM Static   # Name or version of the build that you want to scan. This will be used as the scan name. If omitted, the current date time will be used.
  # scan_timeout: 60                      # Number of minutes to wait for the scan to complete and pass policy.
  # scan_polling_interval: 30             # Interval, in seconds, to poll for the status of a running scan. (30 - 120)
  
applications:
  # Add your applications' config here. These values will override the defaults specified above.
  - app_name: Example                     # Name of the application profile.
    package_source: C:\app\source         # Package source for given source type. If present, auto-packager will be used.
    # OR: 
    # artefact_paths:                     # If auto-packaging is not required, you can remove 'package_source' and add the dirs and/or files to be uploaded here.
    #   - C:\path\to\dir
    #   - C:\path\to\package.zip 
  - app_name: Example 2
    package_source: C:\app\source2