default:
  # Add any default values that will apply for multiple applications here.
  verbose: false                          # Increase output verbosity.
  auto_cleanup: true                      # Automatically remove any packaged artefacts.
  type: directory                         # Package source type, options=[repo, directory (default)].
  strict: true                            # If this field is true, the packaging step will fail on application build failure.
  sandbox_name: Release Candidate         # Name of the sandbox to use when running a sandbox scan or promoting a sandbox scan.
  # branch: main                          # Name of specific branch to scan.
  # version: 02 Jan 2006 15:04PM Static   # Name or version of the build that you want to scan. This will be used as the scan name. If omitted, the current date time will be used.
  wait_for_result: true                   # Wait for the scan to complete and return the status of the scan. [scan_timeout] and [scan_polling_interval] can optionally be set to customize the behaviour.
  # scan_timeout: 120                     # Number of minutes to wait for the scan to complete. Only applicable when [wait_for_result] is set. The default value is: 120
  # scan_polling_interval: 30             # Interval, in seconds, to poll for the status of a running scan. Only applicable when [wait_for_result] is set. The value can be between: 30 - 120. The default value is: 30
  
applications:
  # Add your applications' config here. These values will override the defaults specified above.
  - app_name: Example                     # Name of the application profile.
    package_source: C:\app\source         # Package source for given source type. If present, auto-packager will be used.
    # OR: 
    # artefact_paths:                     # If auto-packaging is not required, you can remove 'package_source' and add the dirs and/or files to be uploaded here.
    #   - C:\path\to\dir
    #   - C:\path\to\package.zip 
  - app_name: Example 2
    package_source: C:\app\source2