name: release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-app:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: ["amd64"]
        os: ["windows"]
    timeout-minutes: 2

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      id: go
      uses: actions/setup-go@v4
      with:
        go-version-file: go.mod

    - name: Go Tidy
      run: go mod tidy && git diff --exit-code

    - name: Go Mod
      run: go mod download

    - name: Go Mod Verify
      run: go mod verify
    
    - name: Build
      run: GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -o out/verapack-${{ matrix.os }}-${{ matrix.arch }}-${{ github.ref_name }}/ -ldflags='-s -w -X "main.Version='${{ github.ref_name }}'"' ./cmd/verapack/

    - name: Create Archive
      run: |
        sudo apt-get install zip gzip tar
        (cd out && zip -r ../verapack-${{ matrix.os }}-${{ matrix.arch }}-${{ github.ref_name }}.zip .)     

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        path: out/*
        if-no-files-found: error
        overwrite: true       
    
  update-docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4 


    - name: Set version in Powershell install script
      run: |
        mkdir out
        sed -i 's/${version}/${{ github.ref_name }}/' install/Install.ps1 > out/Install.ps1

    - name: Minify PowerShell install script
      uses: StartAutomating/PSMinifier@v1.1.3
      with:
        Include: out/*.ps1

    - name: Update README
      run: |
        sed -i '42{r out/Install.min.ps1}' README.md

    - name: Commit changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git checkout -B auto-update-ps-readme
        git add .
        git commit -m "Updated README for tag: '${{ github.ref_name }}'"
        git push

        gh pr create --fill -a @DanCreative
      
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release:
    runs-on: ubuntu-latest
    needs: build-app
    steps:
    - name: Download built artifacts
      uses: actions/download-artifact@v5
      with:
        path: out

    # Documentation: https://github.com/softprops/action-gh-release
    - name: Create Github Release
      uses: softprops/action-gh-release@v2.3.2
      with:
        generate_release_notes: true
        fail_on_unmatched_files: true
        files: |
          out/*.zip
          out/*.msi